/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0cca7449f7cd143ec29b9ae872e29627)
interface __BaseEnv_Env {
	DB: D1Database;
	APP_ORIGIN: "https://jamtytrack.montagnertudor.org";
	HABIT_ID: "b1a7d4c2-9e35-4f18-8a6b-3c0d5e7f2a91";
	GARMIN_SYNC_TOKEN: string;
	ENCRYPTION_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "HABIT_ID" | "GARMIN_SYNC_TOKEN" | "ENCRYPTION_KEY">> {}
}
